import type { BookLane, Lang, PackLane, TraderBoard } from './types'

export const copy = {
  en: {
    brandKicker: 'Limitless',
    brand: 'Maker Desk',
    navBooks: 'Books',
    navPacks: 'Packs',
    navTraders: 'Traders',
    scoring: 'Scoring',
    langToggle: 'FA',
    booksTitle: 'Books you can print volume on without eating the spread.',
    booksLead:
      "Live Limitless CLOB scan. Ranked for tight books, maker-zero fees, rebate/LP markets, and high implied win probability — so you don't farm dead liquidity.",
    scanned: 'Scanned',
    scannedHint: 'active books with a quote',
    shown: 'Shown volume',
    median: 'Median spread',
    tighten: 'tighten filters if empty',
    bestTickets: 'Best tickets now',
    livePacks: 'Live packs',
    allPacks: 'All packs →',
    search: 'Search ticker or title',
    allDomains: 'All domains',
    anyDuration: 'Any duration',
    clobOnly: 'CLOB only',
    rebates: 'Rebates',
    hideThin: 'Hide thin',
    watchlist: 'Watchlist',
    refresh: 'Refresh',
    loadError: 'Could not load Limitless books.',
    empty: 'No books match. Loosen spread, turn off “Hide thin”, or clear search.',
    volume: 'Volume',
    spread: 'Spread',
    winP: 'Win P',
    takeDrag: 'Take drag',
    bestTrade: 'Best trade',
    score: 'score',
    openBook: 'Open book',
    trade: 'Trade',
    share: 'Share',
    ends: 'Ends',
    book: 'Book',
    skip: 'SKIP',
    scoringTitle: 'How the desk ranks books',
    close: 'Close',
    scoringSafe: 'Safest volume — tight yes/no spread, real printed size, CLOB maker fee 0, rebates / LP, not a dead book.',
    scoringVol: 'Most volume — raw USDC printed, still penalized if the spread is a barn door.',
    scoringWin: 'Highest win P — favorite implied probability, but only if you can enter without a wide book or 3% taker buy.',
    scoringTrade:
      'Best trade — a concrete ticket. MAKE rests the favorite bid (fee 0). TAKE only if leftover after spread + taker fee is still ≥ 10¢. Otherwise skip.',
    scoringFoot: 'Taking the favorite near 50¢ costs up to 3% buy + 1.5% sell. Resting a limit is free. Hide thin books and cap spread — that is where volume farming actually leaks.',
    disclaimer:
      'Scores are a desk screen, not financial advice. Makers pay 0% on Limitless CLOBs; takers pay the live fee curve. Wide / thin books lose you more than the fee. Data from the public Limitless API, refreshed about every 30s. Ambassador disclosure: Kaveh is a Limitless partner; market links use referral code YVH0J7QD0S.',
    promo:
      'Ambassador note: trade $30 on Limitless via the referral link and the current promo pays $20 USDC at month-end. Not a return promise — read the book first.',
    promoCta: 'Open Limitless',
    lanes: {
      safe: { label: 'Safest volume', hint: 'Tight book + maker 0% + fills' },
      volume: { label: 'Most volume', hint: 'Where size is already printing' },
      win: { label: 'Highest win P', hint: 'Favorite side without a fee trap' },
      trade: { label: 'Best trade', hint: 'MAKE or TAKE ticket, leftover if right' },
    } satisfies Record<BookLane, { label: string; hint: string }>,
    packsTitle: 'Live Limitless packs. All legs have to hit.',
    packsLead:
      'Curated 2–3 leg parlays, $1–$10 stake, 4% vig already in the multiplier. Ranked by implied hit chance and leftover payout — not by the flashiest name.',
    livePackCount: 'Live packs',
    fromPacks: 'from /parlay/packs',
    topTicket: 'Top ticket',
    waiting: 'waiting on books',
    tenPays: '$10 pays',
    ifEvery: 'if every leg lands',
    buyableOnly: 'Buyable only',
    noPacks: 'No live packs right now.',
    packError: 'Could not load packs.',
    openPack: 'Open pack',
    packFoot:
      'A pack pays only if every leg resolves your way. Multiplier is net of the 4% vig. Live prices move; the number you lock is the one on Limitless when you buy. Not advice.',
    packLanes: {
      best: { label: 'Best ticket', hint: 'Hit chance × payout, not a lottery' },
      safe: { label: 'Most likely', hint: 'Highest joint implied P' },
      juice: { label: 'Highest mult', hint: 'Fattest $10 → payout' },
    } satisfies Record<PackLane, { label: string; hint: string }>,
    tradersTitle: 'Who is actually printing.',
    tradersLead: 'Live Limitless boards — realized PnL and referral take. Search a wallet. Click through to their public profile.',
    board: 'Board',
    leader: 'Leader',
    rows: 'Rows',
    publicApi: 'public Limitless API',
    sortRoi: 'Sort by ROI',
    traderError: 'Could not load traders.',
    wallet: 'Search 0x wallet',
    lookup: 'Lookup',
    lookupMiss: 'Not on this page. All-time traded volume:',
    lookupBad: 'Need a 0x address.',
    traderFoot: 'PnL is realized only — open positions are not in this board. Numbers can lag a few minutes.',
    trader: 'Trader',
    realized: 'Realized',
    roi: 'ROI',
    closedSize: 'Closed size',
    referrer: 'Referrer',
    earned: 'Earned',
    feesMade: 'Fees made',
    referred: 'Referred',
    profile: 'Profile',
    loading: 'loading',
    traderBoards: {
      pnl24h: { label: 'PnL 24h', hint: 'Realized, last day' },
      pnl7d: { label: 'PnL 7d', hint: 'Realized, last week' },
      pnl30d: { label: 'PnL 30d', hint: 'Realized, last month' },
      refs: { label: 'Referrals', hint: 'USDC earned from fees' },
    } satisfies Record<TraderBoard, { label: string; hint: string }>,
  },
  fa: {
    brandKicker: 'لیمیتلس',
    brand: 'میز میکر',
    navBooks: 'بوک‌ها',
    navPacks: 'پک‌ها',
    navTraders: 'تریدرها',
    scoring: 'امتیازدهی',
    langToggle: 'EN',
    booksTitle: 'بوک‌هایی که می‌تونی روشون حجم بزنی، بدون اینکه اسپرد بخوردت.',
    booksLead:
      'اسکن زنده CLOB لیمیتلس. رتبه‌بندی برای اسپرد تنگ، کارمزد صفر میکر، بازارهای ریبیت/LP و احتمال برد بالا — تا نقدینگی مرده را شخم نزنی.',
    scanned: 'اسکن‌شده',
    scannedHint: 'بوک فعال با کوت',
    shown: 'حجم نمایش‌داده‌شده',
    median: 'میانه اسپرد',
    tighten: 'اگر خالی است فیلتر را شل کن',
    bestTickets: 'بهترین بلیت‌های الان',
    livePacks: 'پک‌های زنده',
    allPacks: 'همه پک‌ها ←',
    search: 'جستجوی تیکر یا عنوان',
    allDomains: 'همه دامنه‌ها',
    anyDuration: 'هر بازه‌ای',
    clobOnly: 'فقط CLOB',
    rebates: 'ریبیت',
    hideThin: 'پنهان کردن بوک نازک',
    watchlist: 'واچ‌لیست',
    refresh: 'تازه‌سازی',
    loadError: 'بوک‌های لیمیتلس لود نشد.',
    empty: 'چیزی جور نشد. اسپرد را شل کن، «پنهان کردن بوک نازک» را خاموش کن، یا جستجو را پاک کن.',
    volume: 'حجم',
    spread: 'اسپرد',
    winP: 'احتمال برد',
    takeDrag: 'هزینه تیک',
    bestTrade: 'بهترین ترید',
    score: 'امتیاز',
    openBook: 'باز کردن بوک',
    trade: 'ترید',
    share: 'اشتراک',
    ends: 'پایان',
    book: 'بوک',
    skip: 'رد',
    scoringTitle: 'میز چطور بوک‌ها را رتبه‌بندی می‌کند',
    close: 'بستن',
    scoringSafe: 'امن‌ترین حجم — اسپرد تنگ، حجم واقعی چاپ‌شده، کارمزد میکر صفر، ریبیت/LP، نه بوک مرده.',
    scoringVol: 'بیشترین حجم — USDC خام چاپ‌شده، اگر اسپرد گشاد باشد جریمه می‌شود.',
    scoringWin: 'بالاترین احتمال برد — سمت محبوب، فقط اگر ورود بدون بوک گشاد یا کارمزد ۳٪ تیکر ممکن باشد.',
    scoringTrade:
      'بهترین ترید — بلیت مشخص. MAKE سفارش لیمیت روی بید محبوب است (کارمزد صفر). TAKE فقط اگر بعد از اسپرد و کارمزد تیکر هنوز حداقل ۱۰ سنت باقی بماند.',
    scoringFoot: 'تیک کردن نزدیک ۵۰ سنت تا ۳٪ خرید و ۱.۵٪ فروش هزینه دارد. لیمیت گذاشتن رایگان است. بوک نازک را پنهان کن و اسپرد را محدود کن.',
    disclaimer:
      'امتیازها صفحه میز است، نه توصیه مالی. میکر در CLOB لیمیتلس ۰٪ می‌پردازد؛ تیکر منحنی کارمزد زنده را می‌پردازد. بوک گشاد/نازک بیشتر از کارمزد ضرر می‌زند. داده از API عمومی لیمیتلس، حدود هر ۳۰ ثانیه. افشا: کاوه سفیر لیمیتلس است؛ لینک بازارها کد دعوت YVH0J7QD0S دارند.',
    promo:
      'یادداشت سفیر: با لینک دعوت حداقل ۳۰ دلار ترید کن؛ پروموی فعلی آخر ماه ۲۰ دلار USDC می‌دهد. قول سود نیست — اول بوک را بخوان.',
    promoCta: 'باز کردن لیمیتلس',
    lanes: {
      safe: { label: 'امن‌ترین حجم', hint: 'بوک تنگ + میکر ۰٪ + فیل' },
      volume: { label: 'بیشترین حجم', hint: 'جایی که حجم همین حالا چاپ می‌شود' },
      win: { label: 'بالاترین احتمال برد', hint: 'سمت محبوب بدون تله کارمزد' },
      trade: { label: 'بهترین ترید', hint: 'بلیت MAKE یا TAKE، باقیمانده اگر درست باشد' },
    } satisfies Record<BookLane, { label: string; hint: string }>,
    packsTitle: 'پک‌های زنده لیمیتلس. همه لگ‌ها باید بخورد.',
    packsLead: 'پارلی ۲–۳ لگی، استیک ۱ تا ۱۰ دلار، ویگ ۴٪ داخل ضریب. رتبه‌بندی با شانس برد و پرداخت باقیمانده — نه اسم پرزرق‌وبرق.',
    livePackCount: 'پک‌های زنده',
    fromPacks: 'از /parlay/packs',
    topTicket: 'بهترین بلیت',
    waiting: 'منتظر بوک',
    tenPays: '۱۰ دلار می‌دهد',
    ifEvery: 'اگر همه لگ‌ها بخورد',
    buyableOnly: 'فقط قابل خرید',
    noPacks: 'الان پک زنده‌ای نیست.',
    packError: 'پک‌ها لود نشد.',
    openPack: 'باز کردن پک',
    packFoot: 'پک فقط وقتی می‌پردازد که همه لگ‌ها به نفع تو تمام شود. ضریب بعد از ویگ ۴٪ است. قیمت زنده جابه‌جا می‌شود. توصیه نیست.',
    packLanes: {
      best: { label: 'بهترین بلیت', hint: 'شانس × پرداخت، نه بخت‌آزمایی' },
      safe: { label: 'محتمل‌ترین', hint: 'بالاترین احتمال مشترک' },
      juice: { label: 'بالاترین ضریب', hint: 'چاق‌ترین پرداخت برای ۱۰ دلار' },
    } satisfies Record<PackLane, { label: string; hint: string }>,
    tradersTitle: 'کی واقعاً دارد حجم می‌زند.',
    tradersLead: 'بردهای زنده لیمیتلس — PnL محقق‌شده و درآمد دعوت. والت را جستجو کن. برو روی پروفایل عمومی‌شان.',
    board: 'برد',
    leader: 'لیدر',
    rows: 'ردیف',
    publicApi: 'API عمومی لیمیتلس',
    sortRoi: 'مرتب‌سازی با ROI',
    traderError: 'تریدرها لود نشد.',
    wallet: 'جستجوی والت 0x',
    lookup: 'بررسی',
    lookupMiss: 'روی این صفحه نیست. حجم کل ترید:',
    lookupBad: 'آدرس 0x لازم است.',
    traderFoot: 'PnL فقط محقق‌شده است — پوزیشن باز در این برد نیست. اعداد ممکن است چند دقیقه تأخیر داشته باشند.',
    trader: 'تریدر',
    realized: 'محقق‌شده',
    roi: 'ROI',
    closedSize: 'حجم بسته‌شده',
    referrer: 'معرف',
    earned: 'درآمد',
    feesMade: 'کارمزد ساخته‌شده',
    referred: 'معرفی‌شده',
    profile: 'پروفایل',
    loading: 'در حال لود',
    traderBoards: {
      pnl24h: { label: 'PnL ۲۴ساعته', hint: 'محقق‌شده، روز قبل' },
      pnl7d: { label: 'PnL ۷روزه', hint: 'محقق‌شده، هفته قبل' },
      pnl30d: { label: 'PnL ۳۰روزه', hint: 'محقق‌شده، ماه قبل' },
      refs: { label: 'دعوت‌ها', hint: 'USDC از کارمزد' },
    } satisfies Record<TraderBoard, { label: string; hint: string }>,
  },
} as const

export type Copy = (typeof copy)[Lang]
